notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1 DEMYX_USERNAME=demyx DEMYX_REPOSITORY=elgg

before_install:
  - sudo apt-get install jq
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull alpine
  - docker pull demyx/mariadb
  - docker pull traefik

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker-compose up -d
  - sleep 10
  - docker exec -t elgg sh -c "apk add git composer; cd /var/www && git clone https://github.com/Elgg/Elgg.git"
  - docker cp elgg-installer.php elgg:/var/www/Elgg
  - docker exec -t elgg sh -c "cd /var/www/Elgg; composer install; php elgg-installer.php; mv /var/www/Elgg/elgg-config/settings.php /var/www/html/elgg-config; chown -R www-data:www-data /var/www/html"
  - docker exec -t elgg sh -c "php vendor/bin/elgg-cli plugins:list --status all"

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
